### ISSUE TITLE
Presentación, Evaluación, Rubricas, Citacion y Temario

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/taller#1]
Presentación, Evaluación, Rubricas, Citacion y Temario

![](http://www.itainnova.es/wp-content/uploads/2014/10/Linea_Innovaci%C3%B3n_Ingenieria_Software.jpg)

## EVALUACIÓN

Los trabajos finales por documento estructurado lo crearemos usando Overleaf o el link http://tinyurl.com/isc7tareas en su momento se platicará del Templete IEEE  ya estructurado solo es de redactar los puntos relevantes, con Figuras y Tablas.

## PORTAFOLIO DE EVIDENCIAS
Para nosotros es http://github.com/tectijuana/taller este se estructurará de tal forma que se vean los esfuerzos de cada uno y claro se refleje en la _Sabana GoogleSheet del bloque I-V_

## SABANA CALIFICADOR CON RÚBRICAS
En nuestro URL  *isc7drive* dentro de la carpeta de TALLER DE INVESTIGACION 2 estará la hoja de cálculo con sus nombres,  junto con las ponderaciones de las calificaciones y claro las rúbricas que indican como deben estar los trabajos para recibir este 20%, etc.

## NO HAY EXAMENES SOLO AUTOEVALUACIONES (10 A 20%)
Eso son evaluaciones en linea que puede ustede revisar con anterioridad y autoevaluarse, ya nos ponemos de acuerdo cuando y cuanto valdrá esta autoevaluacion por lo regular es menos de 15% 
Y solo funciona esta durante la hora de clase, no fuera del salón; me refiero no deben entregar pantallazos o impresion de producto.

## USO DE MARKDOWN EN LAS PRESENTACIONES

Recodemos que es obligarorio que exploren el metalenguaje de MarkDown para la presentación de trabajo en plataforma distribuida.

**Comment by IoTeacher** [comment]
## TEMARIO DEL CURSO

[AC010 Taller de Investigacion II.pdf](https://github.com/tectijuana/taller/files/709560/AC010.Taller.de.Investigacion.II.pdf)

**Comment by IoTeacher** [comment]
Revisamos el temario y platicamos lo importante de los BOTS de Slack, para BUSYBOT dejar pendientes y revisiones, y claro SnippetsBot Para los Logros y recordatorios.

**Comment by IoTeacher** [comment]
Como triturar datos estadisticos en Lenguaje R.
Usaremos Mockaroo
![Datos a graficar](https://pbs.twimg.com/media/CwpJKFoVIAALEr_.jpg)

[Para muestro de datos mockdata](http://mockaroo.com/)

Ahora bien, ya sabes los basicos de Lenguaje R, ya conoces la literatura disponible en ISC7DRIVE bien ahora elaborara un marco de 1000 metadatos misterio y grafica en lenguaje R

![](http://www.ats.ucla.edu/stat/r/modules/explor11.gif)

**Comment by IoTeacher** [comment]
![](http://blog.dataglot.com/OrganicBuilder/img/github-logo.jpg)

# GUIA RAPIDA DE GIT CON TUTORIAL

Cuentas con 15 minutos para resolver el tutorial de Github es http://try.github.io
Y envio la guia rápida de git  https://services.github.com/on-demand/downloads/es_ES/github-git-cheat-sheet.pdf

**Comment by IoTeacher** [comment]
Recolección de citaciones de los artículos leídos para después procesarlos en LaTeX.

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/74c50j451WU/0.jpg)](https://www.youtube.com/watch?v=74c50j451WU)

**Comment by IoTeacher** [comment]
[Recuerden usar un templete de Programación en R, ya que es trabajo para 3ras. personas y deben estar bonito el código-presentable](https://www.google.com/search?q=todo+programa+requiere+titulos&oq=todo+programa+requiere+titulos&aqs=chrome..69i57.4409j0j7&sourceid=chrome&ie=UTF-8#q=R+program+template)    

    # *------------------------------------------------------------------
    # | PROGRAM NAME: 
    # | DATE: 
    # | CREATED BY:  
    # | PROJECT FILE:              
    # *----------------------------------------------------------------
    # | PURPOSE:           
    # |
    # *------------------------------------------------------------------
    # | COMMENTS:               
    # |
    # |  1:  
    # |  2: 
    # |  3: 
    # |*------------------------------------------------------------------
    # | DATA USED:               
    # |
    # |
    # |*------------------------------------------------------------------
    # | CONTENTS:               
    # |
    # |  PART 1:  
    # |  PART 2: 
    # |  PART 3: 
    # *-----------------------------------------------------------------
    # | UPDATES:               
    # |
    # |
    # *------------------------------------------------------------------
 
 
     setwd('/Users/wkuuser/Desktop/R Data Sets') # mac 
 
     setwd("P:\\R  Code References\\R Data") # windows
 
     rm(list=ls()) # get rid of any existing data 
     ls() # view open data sets
 
    # IMPORT CSV FILE
 
    YOURDATA <- read.csv("NAME.csv", na.strings=c(".", "NA", "", "?"), encoding="UTF-8")
 
    # *------------------------------------------------------------------
    # |                
    # |
    # |   
    # |
    # |                
    # *-----------------------------------------------------------------
 
    # *------------------------------------------------------------------
    # |                       
    # *-----------------------------------------------------------------

**Comment by IoTeacher** [comment]
## _Favor de acondicionar la tabla con los datos faltantes_

| Matricula 	| Nombre                                	| Slack 	| GitHub 	|
|-----------	|---------------------------------------	|-------	|--------	|
| 14211399  	| ALVARADO SOTO JESUS MANUEL            	|       	|        	|
| 14210446  	| ALVAREZ ORTEGA ESTEPHANIA             	|       	|        	|
| 14211402  	| AQUINO VAZQUEZ OMAR                   	|       	|        	|
| 14211404  	| BARBA ANDRADE JOSUE                   	|       	|        	|
| 14212003  	| BAUTISTA VARGAS JORGE DAMIAN          	|       	|        	|
| 14210445  	| CASTILLO ARAGON WALTER                	|       	|        	|
| 14211412  	| CEBALLOS PILLADO KARINA IVETH         	|       	|        	|
| 14210428  	| CELAYA CARRANCO FAUSTO JAVIER         	|       	|        	|
| 14212013  	| CRUZ ESPINOZA VIANEY KARELI           	|       	|        	|
| 14211418  	| DELGADO VALENCIA JUAN                 	|       	|        	|
| 14211427  	| GAMEZ GOMEZ DIANA KARINA              	|       	|        	|
| 12210376  	| GUTIERREZ PATIÑO DYLCIA ESTEFANIA     	|       	|        	|
| 14210465  	| GUZMAN GARCIA VICTOR RAFAEL           	|       	|        	|
| 14211438  	| HE XUAN YANMING                       	|       	|        	|
| 14211440  	| HERNANDEZ BOCANEGRA MIGUEL ANGEL      	|       	|        	|
| 14212030  	| HIDALGO LOPEZ JUAN CARLOS             	|       	|        	|
| 14211442  	| ILHUICATZI CAMPOS KASSANDRA CITLALLI  	|       	|        	|
| 14211444  	| LAGARDA MENDEZ LUIS MARTIN            	|       	|        	|
| 14212037  	| LOPEZ HERNANDEZ OLIVIA CRISTINA       	|       	|        	|
| 14211446  	| LOPEZ PEREZ WILBERT ALEXANDER         	|       	|        	|
| 14211452  	| MARTINEZ CORONA ANTONIO               	|       	|        	|
| 10210544  	| MARTINEZ REYES JULIO ISMAEL           	|       	|        	|
| 14212044  	| MONTOYA HEREDIA VICTOR JEHOVANY       	|       	|        	|
| 14210427  	| MUNIVE SALDAÑA EVANS JOSUE            	|       	|        	|
| 14210507  	| NODAL CADENA JOSE ANTONIO             	|       	|        	|
| 14211460  	| OLVERA RAMOS ENRIQUE JAVIER           	|       	|        	|
| 13211491  	| ORTEGA SOTELO ALFREDO                 	|       	|        	|
| 14211465  	| RAMIREZ CONTRERAS JAIR                	|       	|        	|
| 13211137  	| RAMIREZ VASQUEZ LUIS FERNANDO         	|       	|        	|
| 14211474  	| ROSAL MACHAIN JORGE LUIS              	|       	|        	|
| 13211430  	| ROSALES GUTIERREZ TERIUS EMILIO       	|       	|        	|
| 14210489  	| ROSALES PINEDA ANGEL                  	|       	|        	|
| 14212059  	| RUBIO ESCALANTE ANGEL DAVID ALEJANDRO 	|       	|        	|
| 14211476  	| SAAVEDRA REGALADO CARLOS ANDRES       	|       	|        	|
| 13211419  	| SALCEDO MORALES JOSE MANUEL           	|       	|        	|
| 14211481  	| SEVILLA OMAÑA VANESSA ITZAYANA        	|       	|        	|
| 14211484  	| SIQUEIROS LEON MIGUEL ALEJANDRO       	|       	|        	|
| 14210515  	| TORRES MARTINEZ ALEJANDRO             	|       	|        	|
| 14211492  	| VERA MALDONADO ERNESTO                	|       	|        	|
| 14212068  	| VILLALOBOS ALCARAZ LUIS EDUARDO       	|       	|        	|
| 13211106  	| VILLEGAS CASTILLO OMAR                	|       	|        	|

**Comment by IoTeacher** [comment]
![](http://www.rcgates.com/psyc/cs_example/learningstyle.jpg)

_Exámen diagnóstico Inventario de estilo de aprendizaje del grupo_

Favor de elaborar el siguiente, contestando con * 0=No gusta, 1=mas o menos y 2=mucho*

http://www.learning-styles-online.com/inventory

Envia un *recorte de pantalla a slack #TALLER*

La Grupo y Clave es:  *isc7taller*

**Comment by abneribarra** [comment]
profesor aun no tengo permisos para subir archivos en github : / ,mi nombre de usuario es abneribarra en github.com y en slack.com es @abneribarra1 ,Gracias!

**Comment by IoTeacher** [comment]
Software ciente que recomiendo para trabajar dentro de windows es:  https://git-for-windows.github.io


![](https://www.virment.com/wp-content/uploads/2015/03/gitforwindows-top.png)

**Comment by IoTeacher** [comment]
# Indicadores de cualidades del trabajo final

|          Criterios          	|                                                                         5                                                                         	|                                                      4                                                     	|                                                                               3                                                                               	|                                                        2                                                        	|                                                                                                  1                                                                                                  	|
|:---------------------------:	|:-------------------------------------------------------------------------------------------------------------------------------------------------:	|:----------------------------------------------------------------------------------------------------------:	|:-------------------------------------------------------------------------------------------------------------------------------------------------------------:	|:---------------------------------------------------------------------------------------------------------------:	|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:	|
| Introducción                	| Elabora una contextualización de los temas a tratar, menciona el objetivo y propósito de la actividad, de forma correcta y precisa.               	| Menciona la contextualización de los temas a tratar, describe el objetivo y propósito de la actividad.     	| Menciona la contextualización del tema sin contemplar todos los temas. Describe el objetivo y propósito de la actividad sin ser redactados de forma correcta. 	| No hace mención de la contextualización de los temas, menciona objetivo y propósito,                            	| El contenido de la información no hace referencia adecuada a la contextualización de los temas ya que no tiene sentido con la materia y la actividad a realizar, no menciona objetivo ni propósito. 	|
| Desarrollo                  	| Desarrolla cada uno de los puntos solicitados, además de que se identifica la relación los reactivos, así como el procedimiento para su solución. 	| Presenta cada uno de los puntos solicitados, se identifica la relación que existe entre cada reactivo.     	| Elabora cada uno de los puntos solicitados, pero no se distingue total relación de los reactivos resueltos.                                                   	| No se presentan todos los contenidos solicitados, además de que existe poca relación entre reactivos resueltos. 	| Falta más del 50% de los contenidos solicitados y existe nula relación de los reactivos resueltos.                                                                                                  	|
| Conclusiones y aportaciones 	| Reconoce los momentos, situaciones y experiencias al elaborar la actividad, así como la interdisciplinaridad entre contenidos.                    	| Distingue los conocimientos adquiridos a lo largo de la materia, así como la importancia de su aplicación. 	| Menciona las experiencias adquiridas durante el desarrollo de la actividad.                                                                                   	| Identifica algunos de los conocimientos adquiridos.                                                             	| No presenta conclusiones ni aportaciones a la actividad.                                                                                                                                            	|

**Comment by IoTeacher** [comment]
Manual de Leng R con ejemplos
http://stat.ethz.ch/R-manual/R-devel/doc/manual/R-intro.html

**Comment by IoTeacher** [comment]
![screen shot 2017-03-25 at 9 30 20 pm](https://cloud.githubusercontent.com/assets/2523851/24328632/26cecb24-11a3-11e7-8206-7ab32e44f485.png)
