### ISSUE TITLE
Bloque 1 De contenido o cuerpo del trabajo comprenden:

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/taller#2]
Bloque 1 Temario
_1 De contenido o cuerpo del trabajo comprenden:
I. Generalidades del proyecto
1.1. Descripción del problema
1.2. Planteamiento del problema
1.3. Objetivos_

**Comment by IoTeacher** [comment]
# Presentación de los estudiantes de proyectos del año pasado (o semestre)

**Comment by 4dri4n** [comment]
Adrian Mendoza Muñoiz
Ciberterrorismo
Si quiero extenderlo, enfocado un poco mas al área de seguridad informática, como prevenir y protegerse.

**Comment by iribe** [comment]
NOMBRE: GABRIELA IRIBE GONZALEZ
SI ME GUSTARIA INVESTIGAR MAS SOBRE DOMOTICA

**Comment by IoTeacher** [comment]
@4dri4n entonces se requiere para nuestro demo semestrar especializarse en seguridad, y cuentas con muchos demos a realizar, pero lo mas marcado a lo que he leído es _seguridad en IoT_ por la falta de estándares. Como _Spoof DNS a arduinos_ con ethernet que esten reportando el clima ...

![](http://img.wonderhowto.com/img/64/29/63588434473076/0/tutorial-dns-spoofing.w1456.jpg)

**Comment by PriscillaE** [comment]
a) NOMBRE: Priscilla Esmerio
b) Titulo del proyecto TDI 1: Criptografía
c) ¿Desea extender este trabajo pasado? Si, quisiera investigar sobre criptografía asimétrica

**Comment by andresmichel** [comment]
|Nombre|Titulo del proyecto TDI 1|Extender este trabajo pasado?|Áreas de interés|
|-|-|-|-|
|Andrés Michel González|...|No|A.I.|

**Comment by alfhedo** [comment]
a) NOMBRE: Jordy Alfredo Bugarin Barron
b) Titulo del proyecto TDI 1: Delitos Informáticos
c) ¿Desea extender este trabajo pasado? si, quiero investigar mas a fondo acerca de los delitos informáticos más recientes

**Comment by IoTeacher** [comment]
@iribe muy bien, esa muy amplio el área, estos dias haremos nuestra área de efecto para realizar nuestro demo.

**Comment by IoTeacher** [comment]
@andresmichel Excelente en estos dias he escuchado mucho de los BOTS y es una área de IA entre muchas.. checa que estaría para considerar en tu demo de trabajo final que le falta al mundo, dicen que  el 2017 es el año de IA. _Y es en serio._

**Comment by scarlettc** [comment]
_**a) Nombre:**_ Scarlett Itzel Oropeza Cruz
_**b) Titulo de proyecto TDI 1:**_ Seguridad Informática
_**c) ¿Desea extender este trabajo pasado?:**_ No
_**d)**_ Inteligencia Artificial

**Comment by IoTeacher** [comment]
@alfhedo perfecto serguridad !! muy buena y amplia opción mucho que trabajar y si asociamos I.A. para sistemas expertos en seguridad es una área de oportunidad.

**Comment by jesshrgz14** [comment]
a) NOMBRE: Jessica Herrera
b) Titulo del proyecto TDI 1: Inteligencia Artificial
c) ¿Desea extender este trabajo pasado? Sí, tal vez enfocandome en la aplicación de esta en la medicina

**Comment by IoTeacher** [comment]
@scarlettc perfecto si esta de interés mucho de Deep Learning y entre otras áreas relevantes. Veamos cuales pueden llamarle la atención o crear nueva propuesta (basadas en IA)

**Comment by IoTeacher** [comment]
@jesshrgz14 muy importante hay bastantes de donde trabajar por ejemplo Bots de medicina... sistemas expertos, etc.

**Comment by IoTeacher** [comment]
@kyloy Perfecto hoy en dia como nos dices video-imagen de 360º - Oculus, etc. me parece exceletne y tengo material para trabajar de inmediato.

**Comment by EddyGaelMR** [comment]
a) Nombre: Manzo Rodelo Eddy Gael 
b) Titulo de proyecto TDI 1:  Inteligencia artificial 
c) ¿Desea extender este trabajo pasado?: No
d) Inteligencia Artificial

**Comment by garduno** [comment]
a) Nombre: Garduño Muñoz Juan Carlos
b) Titulo de proyecto TDI 1: Computación en la nube
c) ¿Desea extender este trabajo pasado?: no
d) Automatización de edificios aplicando tecnología verde

**Comment by IoTeacher** [comment]
@EddyGaelMR es una muy buena área de oportunidad ! gracias.

**Comment by alejandro-espinoza** [comment]
a) Nombre: Alejandro Espinoza
b) Titulo del proyecto TDI 1: Inteligencia Artificial
c) ¿Desea extender este trabajo pasado?. No
d) Inteligencia Artificial en tutores inteligentes

**Comment by andresmichel** [comment]
_**a) Nombre:**_ Andrés Michel González
_**b) Titulo de proyecto TDI 1:**_ :question:
_**c) ¿Desea extender este trabajo pasado?:**_ No
_**d) Área de interés:**_ Inteligencia Artificial 🤖

**Comment by IoTeacher** [comment]
@garduno estará interesantes y claro veamos que resulta al asistente ambiental que hará de Demo.

**Comment by IoTeacher** [comment]
@andresmichel y @alejandro-espinoza Gracias por la coincidencia en elección.

**Comment by ealvaradoa** [comment]
a) Nombre: Edgar Eliud Alvarado Albares
b) Titulo de proyecto TDI 1: Inteligencia Artificial
c) ¿Desea extender este trabajo pasado?: No
d) Delitos informáticos,  basado en la seguridad y la protección de software vulnerabilidades y áreas a mejorar.

**Comment by fabianvillatoro** [comment]
a) Nombre: Carreon Villatoro Jorge Fabian
b) Titulo de proyecto TDI 1: Domotica( mobil)
c) ¿Desea extender este trabajo pasado?: No
d) Domotica

**Comment by salcedojose** [comment]
# Salcedo Morales Jose Manuel
**Videojuegos**
_(sin aplicacion)_

**¿Desea extender este trabajo pasado?** Claro que **si!** Ya que el trabajo pasado fue de solo investigacion, estoy mas interesado en una aplicacion que le pueda dar.

**Comment by EstephaniaAlvarez** [comment]
**a) Nombre:**  Estephania Alvarez Ortega
**b)Titulo del Proyecto TD1:** 
**c) ¿Desea extender el trabajo?:** No
**d)Area de interés:** Inteligencia Artificial

**Comment by IoTeacher** [comment]
@salcedojose iniciaremos con Unity. ! dejeme arreglarle un respado de este fabuloso software.

**Comment by EvansMunive** [comment]
a) Nombre: Evans Josue Munive Saldaña
b)Titulo del Proyecto TD1:
c) ¿Desea extender el trabajo?: No
d)Area de interés: Inteligencia Artificial para diferentes áreas (casa, hospitales, etc.)

**Comment by thecristopher** [comment]
a) Nombre: Cristopher Alexander Cervantes Morales
b) Titulo de proyecto TDI 1: ?
c) ¿Desea extender este trabajo pasado?: No.
d) Área de interés: Videojuegos!

**Comment by fsandoval-z** [comment]
a) Nombre: Fernando Alexis Sandoval Zavala
b) Titulo de proyecto TDI 1: 
c) ¿Desea extender este trabajo pasado?: No.
d) Área de interés: Realidad Virtual.

**Comment by EduardoAlejandroOrtizRamirez** [comment]
a) NOMBRE:Ortiz Ramirez Eduardo Alejandro
b) Titulo del proyecto TDI 1: Evolucion de las Pantallas
c) ¿Desea extender este trabajo pasado? N
d) Me gustaria investigar sobre Videojuegos con Unity

**Comment by guzman-garcia** [comment]
a) NOMBRE: Guzmán Garcia Victor Rafael
b) Titulo del proyecto TDI 1: 
c) ¿Desea extender este trabajo pasado? No
d) Área de interés: Inteligencia Artificial

**Comment by irnh99** [comment]
a) NOMBRE: Núñez Harper Iván Rael
b) Titulo del proyecto TDI 1: 
c) ¿Desea extender este trabajo pasado? No
d) Prefereria investigar sobre aplicacion  de tecnologias de desarrollo

**Comment by sanchezcesar** [comment]
a) Nombre: Sánchez Casas César Gabriel
b) Titulo del proyecto TDI 1: 
c) ¿Desea extender este trabajo pasado? No 
d) Área de interés: Realidad Virtual

**Comment by cristianvega** [comment]
a) Nombre: Vega Vega Cristian Alexis
b) Titulo de proyecto TDI 1: 
c) ¿Desea extender este trabajo pasado?: No
d) Área de interés: Domotica

**Comment by jesuszh** [comment]
a) Nombre: Zaragoza Hernandez Jesus Ernesto
b) Titulo de proyecto TDI 1: From bit to bit
c) ¿Desea extender este trabajo pasado?: No
d) Área de interés: Relacion entre musica y computacion

**Comment by IoTeacher** [comment]
@jesuszh entendido, entonces hay pocas revistas de música-computo, seria de que leyeras para ver el contexto de la innovación para la investigación.

**Comment by IoTeacher** [comment]
@EduardoAlejandroOrtizRamirez excelente, como que estoy viendo que en Tec hay un pequeño grupo de desarrolladores en Unity el semestre pasado estuve con 3 de ellos.

**Comment by nodal-cadena** [comment]
a) NOMBRE: Nodal Cadena Jose Antonio
b) Titulo del proyecto TDI 1: Applicaciones IoT
c) ¿Desea extender este trabajo pasado? No
d) Conexión IoT con Redes -- Desarrollos de Proyectos en la Empresa

**Comment by danielvizuet** [comment]
a) NOMBRE: Daniel Alfonso Flores Vizuet
b) Titulo del proyecto TDI 1: Historia de los celulares
c) ¿Desea extender este trabajo pasado? Si

**Comment by IoTeacher** [comment]
* Domotica - revisando MOOCS ROS Robotics
* Seguridad - bastante
* Musica --: Alexa Amazon Asistente de voz
* IA  bastante a inv.
* Juegos -- Unity
* Realidad virtual -- listo
* Criptografía  -Seguridad
* medicina  - Revistas/CHECAR
 
TINYURL.COM/ISC7DRI

**Comment by IoTeacher** [comment]
@jesshrgz14 buenas tardes localice un eBook de "futuro de medicina" escrito por un autor experto en el área estará en Slack. Favor de leerlo, veo ahi mucho de donde pueda aterrizar tu investigación y demo-propuesta.

https://www.amazon.com/My-Health-Revolutionary-Technologies-Healthier/dp/6158026107/ref=as_li_ss_tl?s=books&ie=UTF8&qid=1441529406&sr=1-1&keywords=my+health+upgraded&pebp=1441529410230&perid=01W1V4CWZ0PNYVR7GKFQ&linkCode=sl1&tag=medicfutur-20&linkId=f785d5a41ab3c7bb9244b23c820ed7e2

Mande el Ebook a Slack

**Comment by aquinin94** [comment]
a) NOMBRE: Sergio Alan Aquino Vazquez
b) Titulo del proyecto TDI 1: Sistemas Operativos
c) ¿Desea extender este trabajo pasado? Si
