### ISSUE TITLE
Bloque 1 Evaluación y complementación del protocolo de investigación.

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/taller#3]
Bloque 1 Evaluación y complementación del protocolo de investigación.

![](https://i.ytimg.com/vi/czLI3oLDe8M/maxresdefault.jpg)

# CURSOS EDX DE DEEP LEARNING (LIBRES DE AUDITAR)
https://www.edx.org/course?search_query=machine+learning

----
![](http://braindegeek.com/wp-content/uploads/2016/04/logo-twitter-2015-300x206.png)

Feed de Twitter de #DEEPLEARNING
https://twitter.com/search?q=%23deeplearning&src=tyah

**Comment by IoTeacher** [comment]
# Rubrica de practica 1 

<img width="553" alt="rubrica r" src="https://cloud.githubusercontent.com/assets/2523851/22449556/c73f48d0-e715-11e6-9c4b-fabebb93c1b7.png">

**Comment by IoTeacher** [comment]
Platicas que hemos visto fue

Google CAR autonomouse


# Visión por computadora hoy 2015 por Ing. Fei-Fei Li

![fei](https://cloud.githubusercontent.com/assets/2523851/22575422/42be79a8-e96a-11e6-912f-13731f67af7b.PNG)

http://www.ted.com/talks/fei_fei_li_how_we_re_teaching_computers_to_understand_pictures

**Comment by IoTeacher** [comment]
# ACTIVACIÓN DE SERVICIOS AWSEDUCATE PARA INVESTIGADORES

![](http://www.cloudtalk.it/wp-content/uploads/2015/05/aws-educate-formazione.png)



| INVESTIGADOR                            	| AWSEducate       	| OBSERVACIONES           	|
|-----------------------------------------	|------------------	|-------------------------	|
| ALVARADO ALBARES EDGAR ELIUD            	|                  	| :sleeping:              	|
| ALVAREZ ORTEGA ESTEPHANIA               	|                  	| :sleeping:              	|
| AQUINO VAZQUEZ SERGIO ALAN              	|                  	| :sleeping:              	|
| BUGARIN BARRON JORDY ALFREDO            	|                  	| :sleeping:              	|
| CARREON VILLATORO JORGE FABIAN          	|                  	| :sleeping:              	|
| CERVANTES MORALES CRISTOPHER ALEXANDER  	|                  	| :sleeping:              	|
| DIAZ CEJA JESUS DAVID                   	|                  	| :sleeping:              	|
| ESMERIO COSILION PRISCILLA              	|                  	| :sleeping:              	|
| ESPINOZA COVARRUBIAS SILVERIO ALEJANDRO 	|                  	| :sleeping:              	|
| FLORES VIZUET DANIEL ALFONSO            	|                  	| :sleeping:              	|
| GARCIA PERAZA ALEXIS DALY               	|                  	| :sleeping:              	|
| GARDUÑO MUÑOZ JUAN CARLOS               	|                  	| :sleeping:              	|
| GASTELUM ALEMAN CRISTOBAL               	|                  	| :sleeping:              	|
| GASTELUM NIEVES CARLOS                  	|                  	| :sleeping:              	|
| GONZALEZ BUSTOS LUIS ANDRES             	|                  	| :sleeping:              	|
| GUZMAN GARCIA VICTOR RAFAEL             	|                  	| :sleeping:              	|
| HERNANDEZ LOPEZ AARON DANIEL            	|                  	| :sleeping:              	|
| HERRERA GARCIA DIANA GABRIELA           	|                  	| :sleeping:              	|
| HERRERA GONZALEZ JESSICA                	|                  	| :sleeping:              	|
| IBARRA PADIERNA ABNER JHAIR             	|                  	| :sleeping:              	|
| IRIBE GONZALEZ GABRIELA                 	|                  	| :sleeping:              	|
| MANZO RODELO EDDY GAEL                  	|                  	| :sleeping:              	|
| MENDOZA MUÑOZ ADRIAN                    	|                  	| :sleeping:              	|
| MICHEL GONZALEZ ANDRES                  	|                  	| :sleeping:              	|
| MUNIVE SALDAÑA EVANS JOSUE              	|                  	| :sleeping:              	|
| NODAL CADENA JOSE ANTONIO               	|                  	| :sleeping:              	|
| NUÑEZ HARPER IVAN RAEL                  	|                  	| :sleeping:              	|
| OCHOA MIGUEL ANGEL                      	|                  	| :sleeping:              	|
| OROPEZA CRUZ SCARLETT ITZEL             	|                  	| :sleeping:              	|
| ORTIZ RAMIREZ EDUARDO ALEJANDRO         	|                  	| :sleeping:              	|
| PATIÑO PEINADO CRISTIAN ANTONIO         	|                  	| :sleeping:              	|
| RAMIREZ VALENZUELA JESUS ANDRES         	|                  	| :sleeping:              	|
| RAMOS HERNANDEZ JUAN CARLOS             	|                  	| :sleeping:              	|
| ROSALES PINEDA ANGEL                    	|                  	| :sleeping:              	|
| SALCEDO MORALES JOSE MANUEL             	|                  	| :sleeping:              	|
| SANCHEZ CASAS CESAR GABRIEL             	|                  	| :sleeping:              	|
| SANDOVAL ZAVALA FERNANDO ALEXIS         	|                  	| :sleeping:              	|
| URIAS JACOBO EDWIN ISAAC                	|                  	| :sleeping:              	|
| VEGA VEGA CRISTIAN ALEXIS               	|                  	| :sleeping:              	|
| VILLANUEVA HERNANDEZ FRANCISCO JONATHAN 	|                  	| :sleeping:              	|
| ZARAGOZA HERNANDEZ JESUS ERNESTO        	|                  	| :sleeping:              	|
| ZAZUETA SAPIEN OSCAR ERNESTO            	|                  	| :sleeping:              	|
|                                         	| :+1: = Activado. 	| :confused: = En Proceso 	|

**Comment by IoTeacher** [comment]
# DOCUMENTACION
https://aws.amazon.com/documentation/ec2/


# RECUERDEN DE "NO CERRAR LAB" EVITANDO SE PIERDAN SUS CREDITOS EN AWS.

![no cerrar lab por 1 ano](https://cloud.githubusercontent.com/assets/2523851/22719571/f4e0aa0e-ed5a-11e6-845f-7775908b8bc3.jpeg)

**Comment by oscarglez1** [comment]
NO estoy en la lista, espero tener pronto mi correo institucional

**Comment by IoTeacher** [comment]
# IP de Servidores AMI

![las ips](https://cloud.githubusercontent.com/assets/2523851/22765441/1c196e7e-ee25-11e6-8692-dd9e59e87499.PNG)

**Comment by IoTeacher** [comment]
# PARA MAC Y LINUX ES DIRECTO EN CONSOLA LA CONEXIÓN
![linux mac](https://cloud.githubusercontent.com/assets/2523851/22765529/aef9fee8-ee25-11e6-8911-af8c9463cb0b.PNG)

**Comment by IoTeacher** [comment]
# SOLO WINDOWS OCUPAS DESCARGAR EL PUTTY FULL Y WINSCP

-  http://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html?
-  http://winscp.net
-  En MAC es http://www.cyberduck.ch   _Creo que ya lo liberaron para Win10_

**Comment by IoTeacher** [comment]
# CONVERTIR LLAVE *.PEM A *.PPK  VIA PUTTY-GEN

## Abrir PUTTY-GEN  **Import** y Salvar como llave privada (*.ppk)

![putty](https://cloud.githubusercontent.com/assets/2523851/22765865/573d6ee0-ee27-11e6-8446-5ffda1e8a155.PNG)

**Comment by IoTeacher** [comment]
![](http://mobilemarketingmagazine.com/wp-content/uploads/2016/12/10-Amazon-AI-1024x341.jpg)

# PARA DESARROLLO EN INTELIENCIA ARTIFICIAL

<img width="1655" alt="renesolis" src="https://cloud.githubusercontent.com/assets/2523851/22772030/232245a4-ee4f-11e6-9497-e929167126f1.png">

> AWS ofrece una familia de servicios de IA que proporcionan tecnologías de aprendizaje automático y profundo para satisfacer sus distintos casos de uso y necesidades. Los servicios de Amazon AI ponen tecnologías de comprensión del lenguaje natural (NLU), reconocimiento automático del habla (ASR), búsqueda visual y reconocimiento de imágenes, texto a habla (TTS) y aprendizaje automático (ML) al alcance de todos los desarrolladores. Amazon Lex facilita la creación de chatbots de texto y voz sofisticados, con tecnología de Alexa. Amazon Rekognition proporciona reconocimiento de imágenes basado en el aprendizaje profundo. Amazon Polly convierte el texto en habla realista, y Amazon Machine Learning le permite crear aplicaciones de ML inteligentes con rapidez. Los servicios de Amazon AI facilitan el desarrollo de aplicaciones interplataforma que se implementan con seguridad en la fase de producción. Los servicios de Amazon AI están totalmente administrados y, por lo tanto, se escalan con facilidad con baja latencia y se encuentran disponibles a bajo costo. Los servicios de Amazon AI le permiten concentrarse en definir y crear una nueva generación de aplicaciones capaces de ver, oír, hablar, entender e interactuar con el mundo que le rodea.

**Comment by IoTeacher** [comment]
![ia robots](https://cloud.githubusercontent.com/assets/2523851/22869596/3d14c4b0-f155-11e6-9134-b24bf208c60e.jpg)


# Diferencia entre  Machine Learning vs Data Scence vs AI vs Deep Learning
http://www.datasciencecentral.com/profiles/blogs/difference-between-machine-learning-data-science-ai-deep-learning

**Comment by IoTeacher** [comment]
# Recordatorio de como conectarnos a AMI AWSEducate via Windows

 [![IMAGE ALT TEXT HERE](http://img.youtube.com/vi/dZyFzUvJQMc/0.jpg)](http://www.youtube.com/watch?v=dZyFzUvJQMc)

**Comment by IoTeacher** [comment]
# Jeremy Howards: The wonderful and terrifying implications of computers that can learn

http://www.ted.com/talks/jeremy_howard_the_wonderful_and_terrifying_implications_of_computers_that_can_learn

**Comment by IoTeacher** [comment]
# Precios de Machine Learning
https://aws.amazon.com/es/machine-learning/pricing/

**Comment by IoTeacher** [comment]
# CIERRE BLOQUE 1


![](https://4.bp.blogspot.com/-wL37hErcPfw/Vu2dK4UqpmI/AAAAAAAAAnI/Y_2bUESP1mUfprYCdmA0WJj4VjbOHRsVg/s1600/Captura%2Bde%2Bpantalla%2B2015-08-08%2Ba%2Blas%2B04.17.22.png)

##  Entrega del Certificado de TERMINACIÓN del curso de "Técnico en BIG DATA" por la fundación Carlos Slim

https://capacitateparaelempleo.org/pages.php?r=.tema&tagID=2289

Enviar el PDF a http://isc7.slack.com junto con conclusión del curso terminado.

----

Elaboración del DEMO de Machine Learning con Amazon Web Services mara MERCADOTECNIA que esta en la ruta http://docs.aws.amazon.com/machine-learning/latest/dg/tutorial.html

**Comment by IoTeacher** [comment]
# A Friendly Introduction to Machine Learning ( sin experiencia previa incluye casos practicos)
[![A Friendly Introduction to Machine Learning](http://img.youtube.com/vi/IpGxLWOIZy4/0.jpg)](http://www.youtube.com/watch?v=IpGxLWOIZy4)

----

# AWS Video de Machine Learning (ML) 1 hora visión general del demo anterior

[![AWS Summit Series 2016 | Chicago - Getting Started with Amazon Machine Learnings](http://img.youtube.com/vi/6a4CTf5uc5c/0.jpg)](http://www.youtube.com/watch?v=6a4CTf5uc5c)

----

# TUTORIALES ESPECIFICOS
## Introducing AWS Machine Learning
[![Introducing AWS Machine Learning](http://img.youtube.com/vi/w4lPqUpeFAA/0.jpg)](http://www.youtube.com/watch?v=w4lPqUpeFAA)

 # Using AWS Machine Learning
[![Using AWS Machine Learning](http://img.youtube.com/vi/sTFTxMm6bGI/0.jpg)](http://www.youtube.com/watch?v=sTFTxMm6bGI)

----

**Comment by oscarglez1** [comment]
profe donde esta la liga para aceder al examen ?
